### PR TITLE
Review of German translations

### PR DESCRIPTION
**Pull request by kdupke**
[first time I issue a pull request, please let me know if I should do differently]

Some strings I was not able to check/translate as it's unclear to me where they appear.

### CODE REVIEW

**Comment by billmeek** [comment]
Danke sehr!

I see your point about not knowing where the strings appear.

I don't think I'll try Google translate again. Translating the original
English from app/src/main/res/values/strings.xml may have been
easier. Also, the strings that don't need to be translated are marked
there.

If you have a chance, please take a look at: app/src/main/res/values-de/arrays.xml
There are only 7 strings that need translating in that file.

Finally, the following will pop up when someone swipes down to refresh the
Watch Recordings page: "Recordings Updated!". If you could translate that
and comment here, I'll add that via Android Studio.

Thanks again for all your help.

**Comment by kdupke** [comment]
> Finally, the following will pop up when someone swipes down to refresh
> the Watch Recordings page: "Recordings Updated!". If you could translate
> that and comment here, I'll add that via Android Studio.

I can't refresh by swiping down, but when I hit the sync button I get a 'update recorded programs'.

The translation for this is

* update recorded programs running -> "Abgleich Aufnahmen läuft"
* recorded programs updated -> "Abgleich Aufnahmen abgeschlossen"

**Comment by kdupke** [comment]
> If you have a chance, please take a look at: app/src/main/res/values-de/arrays.xml
> There are only 7 strings that need translating in that file.

Is there something other to translate then these 5 strings? (Auto is fine for German, too)
> <string-array name="watch_videos_tabs">
> <item>Kino</item>
> <item>TV</item>
> <item>Home Movies</item>
> <item>Musik Videos</item>
> <item>Erwachsene</item>
> </string-array>

Have not found the place in the app where these categories are used.

**Comment by kdupke** [comment]
> Translating the original English from app/src/main/res/values/strings.xml may have been
> easier.

Will do later, might be early next week.

**Comment by billmeek** [comment]
@kdupke, Kino...Erwachsene should appear in Watch Videos as
tabs. You can  press them or swipe left/right. They are from the
MythTV database mythconverg.videometadata.contenttype.

Erwachsene is Google translate's idea of Adult and you won't
see it unless you go into 'Einstellung' and allow it.

If you don't see them, please let me know what version of the app
you're running (Just swipe right to view the Navigation Drawer, it's
near the top on the right.) And mention the type of device you're
running e.g. Nexus 7 please. I'm using 1.1.12 building from source,
so a few commits above the latest Alpha release.

**Pull request merged**
